In [8]:
import numpy as np
import pandas as pd


df=pd.read_csv('spam.csv',encoding="latin1")

In [9]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [10]:
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace=True)

In [12]:
df.shape

(5572, 2)

In [13]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [14]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Hashir\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [15]:
stop_words = set(stopwords.words('english'))
ps = PorterStemmer()
import re

def preprocess(text):
    text=text.lower()
    text= re.sub(r'[^a-z\s]', '', text)
    tokens = text.split()
    tokens= [ps.stem(word) for word in tokens if word not in stop_words]
    return ' '.join(tokens)

df['cleaned']=df['v2'].apply(preprocess)

In [16]:
df.head()

,v1,v2,cleaned
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,ham,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entri wkli comp win fa cup final tkt st m...
3,ham,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah dont think goe usf live around though

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['v1']=le.fit_transform(df['v1'])

In [18]:
df.head()

,v1,v2,cleaned
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entri wkli comp win fa cup final tkt st m...
3,0,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,0,"Nah I don't think he goes to usf, he lives aro...",nah dont think goe usf live around though

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer= TfidfVectorizer()
X= vectorizer.fit_transform(df['cleaned']).toarray()

In [21]:
from sklearn.model_selection import train_test_split
y=df['v1']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train, y_train)
print(model.score(X_test, y_test))

0.9613152804642167

In [25]:
if (model.predict(vectorizer.transform(['Congratulations! You have won a lottery of $1000. Claim your prize now.']).toarray()))==1:
    print("Spam")
else:
    print("Ham")

Spam

In [26]:
if (model.predict(vectorizer.transform(['Congratulations ypu are slelected.']).toarray()))==1:
    print("Spam")
else:
    print("Ham")

Ham